### ISSUE TITLE
All swerve modules turn to same angle?

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#1]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/8d7d751faee160dc6bd9e469b09abe532aa4bee6/src/main/java/org/team199/robot/subsystems/Drivetrain.java#L102-L105

Are you sure that's right?

**Comment by alexander-mcdowell** [comment]
Yeah, definitely not. Darn you copy/paste!
