### ISSUE TITLE
Wrong speeds used to update odometry

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#11]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/757b589ce52184cbf9e9a05e871f30b99bf815c6/src/main/java/org/team199/robot/subsystems/Drivetrain.java#L228-L230

Why use the non-normalized speeds to update the odometry? The normalized speeds are the speeds that we actually request from the controllers so they should be closer to the real speed. Right?

**Comment by alexander-mcdowell** [comment]
I guess so. I was trying to get as close to the original values of fwd, strafe, and rcw, however, those are only the desired values, and are not the closest set of values to the robot's actual fwd, strafe, and rcw. Doing forward kinematics with the normalized states might be more accurate.
