### ISSUE TITLE
getModuleAngle() should use quadrature encoder values for higher accuracy

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#13]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/6eac3a6ed751842a42228470184bb055a73acbb0/src/main/java/org/team199/robot/SwerveModule.java#L86

The analog encoder values may be somewhat inconsistent especially around zero.

**Comment by alexander-mcdowell** [comment]
Should we include some kind of offset so that an output of 0 radians from getModuleAngle corresponds with facing straight forward? Or does it not matter what 0 radians corresponds to as long as all methods which use the module angle use the same formula?

**Comment by brettle** [comment]
What does `HomeAbsolute` do?

**Comment by alexander-mcdowell** [comment]
Okay, so we are assuming that HomeAbsolute is always called first before we get the module angle. I will make it clear that one should call HomeAbsolute before doing any driving in order to avoid screwing up the odometry.

**Comment by brettle** [comment]
Driving itself won't work correctly if `HomeAbsolute` hasn't been called.

**Comment by alexander-mcdowell** [comment]
Oh yeah, because of the (encoderPosition / gearRatio) % 1 line in shouldReverse() and convertAngle(). Do you think we should make HomeAbsolute called immediately when the robot initializes so that we don't forget (or other team members using the robot don't forget).

**Comment by brettle** [comment]
Yes. I just created issue #16 to cover that.
