### ISSUE TITLE
Clarify meaning of frameLength and frameWidth

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#2]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/8d7d751faee160dc6bd9e469b09abe532aa4bee6/src/main/java/org/team199/robot/Constants.java#L26-L27

Based on how these are used, they don't correspond to the length and width of the *frame*, right?

**Comment by alexander-mcdowell** [comment]
I changed the constants to wheelBase and trackWidth which I believe are the correct terms. I got them from this link: https://www.chiefdelphi.com/uploads/default/original/3X/e/f/ef10db45f7d65f6d4da874cd26db294c7ad469bb.pdf

**Comment by brettle** [comment]
Looks good.
