### ISSUE TITLE
SwerveModule cleanup

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#20]
Address issue #18 before addressing this.

If a method is never called, remove it to simplify the code.

If a method is a one-liner that is only called from one place (e.g. `updateSmartDashboard()`), remove the method and put it's implementation in the place where it is called. That will simplify the code and make it easier to see exactly what it does.

If a method does not need to be called from another class, make it private so it isn't called when it shouldn't be.

If a method takes a parameter that hides a field in the class, remove the parameter.

**Comment by brettle** [comment]
You've made good progress on this, but `setAngle()`, `setSpeed()`, and `getAngle()` are all still public.

**Comment by alexander-mcdowell** [comment]
I don't see a getAngle() function.

**Comment by alexander-mcdowell** [comment]
Nvm getModuleAngle()
