### ISSUE TITLE
Make a BaseDrivetrain Class that can be extended by two different Drivetrains

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/SwerveDrive#21]
The WPILib implementation of Drivetrain and the Custom implementation are separated into two different classes that both inherit common methods from BaseDrivetrain. This removes the need for the implementation enum and increases legibility.

**Comment by brettle** [comment]
Almost there. The methods that are overriden in the subclasses should be annotated with `@override` and `CustomDrivetrain.updateOdometry()` should be protected instead of public.
