### ISSUE TITLE
Odometry not updating correctly

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#25]
At least part of the problem is that this method has a bug:

https://github.com/DeepBlueRobotics/SwerveDrive/blob/b4b16330076addc2eda3ecb479ac0f0333943382/src/main/java/org/team199/robot/SwerveModule.java#L143-L145

**Comment by alexander-mcdowell** [comment]
Please tell me it isn't an order of operations issue again... If so, then multiplication takes precedence over modulo and that screws up the result.

**Comment by brettle** [comment]
Fixed as of 80500133ed41f091ec379e16dd1f14e11083b8f7.
