### ISSUE TITLE
SwerveMath.normalize() does not normalize properly

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#4]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/8d7d751faee160dc6bd9e469b09abe532aa4bee6/src/main/java/org/team199/lib/SwerveMath.java#L35-L46

Consider what happens when some of the speeds are negative.
Consider what happens when all of the speeds are small.
Consider using SwerveDriveKinematics.html.normalizeWheelSpeeds() instead: https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveKinematics.html#normalizeWheelSpeeds(edu.wpi.first.wpilibj.kinematics.SwerveModuleState%5B%5D,double)

**Comment by alexander-mcdowell** [comment]
I committed a fix to issue #3 and #4 and I tested it on some test cases.(positive values less than 1, positive values more than 1, small values, negative values, etc.) I believe it preserves the ratio between each of the values.

**Comment by brettle** [comment]
Definitely better but more complicated than necessary, IMO.

What purpose does ` && (0.0 < maximum)` play in this line:
https://github.com/DeepBlueRobotics/SwerveDrive/blob/7089cd1ac9c49b86c532a1c3d9c8c3e810fbcb35/src/main/java/org/team199/lib/SwerveMath.java#L44
?
Do you need to handle the `maximum == 0.0` case specially?
What is a more appropriate initial value for `maximum`?

**Comment by brettle** [comment]
Is there a good reason you aren't just using normalizeWheelSpeeds()?
