### ISSUE TITLE
Missing conversion from ground speed to motor percentage

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/SwerveDrive#6]
https://github.com/DeepBlueRobotics/SwerveDrive/blob/8d7d751faee160dc6bd9e469b09abe532aa4bee6/src/main/java/org/team199/robot/subsystems/Drivetrain.java#L116-L119

**Comment by brettle** [comment]
This still appears to be a problem.

**Comment by alexander-mcdowell** [comment]
Can you elaborate on what you mean by "conversion from ground speed to motor percentage"? Is this a normalization issue that can be solved by SwerveDriveKinematics.normalizeWheelSpeeds(), or is it a separate problem?

**Comment by brettle** [comment]
It is a separate problem. What are the units of the values of the first parameter passed to `SwerveModule.move()` here?
https://github.com/DeepBlueRobotics/SwerveDrive/blob/5667093e42649cd34a5ff0aad654bcc571f1c7b2/src/main/java/org/team199/robot/subsystems/Drivetrain.java#L230

If you trace down into `SwerveModule.move()`, it looks like no unit conversion is done in the computations that use that first parameter to determine the value to eventually pass to `set()` here: https://github.com/DeepBlueRobotics/SwerveDrive/blob/5667093e42649cd34a5ff0aad654bcc571f1c7b2/src/main/java/org/team199/robot/SwerveModule.java#L30

**Comment by alexander-mcdowell** [comment]
Is all that needs to be done is divide by the maximum attainable speed before passing into move()? That way, the units in m/s can be converted to a percentage value of the maximum speed.

**Comment by brettle** [comment]
That needs to happen somewhere. I'd argue that it probably belongs in
SwerveModule somewhere.

--Dean

**Comment by brettle** [comment]
Fixed.
